[package]
name = "delay-notify"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notify-rust="4.5"
clap = { version = "3.0", features = ["derive"] }
